interact:
  enabled: true
  materials:
    - WHEAT_SEEDS
    - LEGACY_SEEDS
    - LEGACY_AIR
    - LEGACY_POTATO_ITEM
throw:
  enabled: true
  materials:
    - EGG
    - SNOWBALL
    - EXPERIENCE_BOTTLE
break:
  enabled: true
  materials:
    - WOODEN_SWORD
    - WOODEN_AXE
    - WOODEN_PICKAXE
    - WOODEN_HOE
    - WOODEN_SHOVEL
    - LEGACY_WOOD_SWORD
    - LEGACY_WOOD_AXE
    - LEGACY_WOOD_PICKAXE
    - LEGACY_WOOD_HOE
    - LEGACY_WOOD_SPADE
    - STONE_SWORD
    - STONE_AXE
    - STONE_PICKAXE
    - STONE_HOE
    - STONE_SHOVEL
    - LEGACY_STONE_SWORD
    - LEGACY_STONE_AXE
    - LEGACY_STONE_PICKAXE
    - LEGACY_STONE_HOE
    - LEGACY_STONE_SPADE
    - IRON_SWORD
    - IRON_AXE
    - IRON_PICKAXE
    - IRON_HOE
    - IRON_SHOVEL
    - LEGACY_IRON_SWORD
    - LEGACY_IRON_AXE
    - LEGACY_IRON_PICKAXE
    - LEGACY_IRON_HOE
    - LEGACY_IRON_SPADE
    - GOLDEN_SWORD
    - GOLDEN_AXE
    - GOLDEN_PICKAXE
    - GOLDEN_HOE
    - GOLDEN_SHOVEL
    - LEGACY_GOLD_SWORD
    - LEGACY_GOLD_AXE
    - LEGACY_GOLD_PICKAXE
    - LEGACY_GOLD_HOE
    - LEGACY_GOLD_SPADE
    - DIAMOND_SWORD
    - DIAMOND_AXE
    - DIAMOND_PICKAXE
    - DIAMOND_HOE
    - DIAMOND_SHOVEL
    - LEGACY_DIAMOND_SWORD
    - LEGACY_DIAMOND_AXE
    - LEGACY_DIAMOND_PICKAXE
    - LEGACY_DIAMOND_HOE
    - LEGACY_DIAMOND_SPADE
    - NETHERITE_AXE
    - NETHERITE_PICKAXE
    - NETHERITE_HOE
    - NETHERITE_SHOVEL
consume:
  auto:
    enabled: true
  enabled: true
  materials:
    - SWEET_BERRIES
    - RABBIT_STEW
    - BREAD