name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mc-version:
          - '1.20.1'
          - '1.20.4'
          - '1.21.1'
          - '1.21.4'
          - '1.21.8'
          - '1.21.9'
          - '1.21.10'
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build JAR with Gradle
        run: ./gradlew -PpaperApiVersion=${{ matrix.mc-version }}-R0.1-SNAPSHOT assemble